fixtures:
    symlinks:
      opendnssec: "#{source_dir}"
    forge_modules:
      stdlib: "puppetlabs/stdlib"
      concat: "puppetlabs/concat"
      mysql: "puppetlabs/mysql"
      cron_core: "puppetlabs/cron_core"
    repositories:
      augeas: "https://github.com/camptocamp/puppet-augeas.git"
