fixtures:
    symlinks:
      opendnssec: "#{source_dir}"
    forge_modules:
      stdlib: "puppetlabs/stdlib"
      concat: "puppetlabs/concat"
      mysql: "puppetlabs/mysql"
      tea: "icann/tea"

