---
sudo: false
dist: trusty
language: ruby
cache: bundler
bundler_args: --without system_tests development
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
env: ["CHECK=rubocop", "PUPPET_VERSION=\"~> 4.6.0\" STRICT_VARIABLES=yes CHECK=test", "PUPPET_VERSION=\"~> 4.7.0\" STRICT_VARIABLES=yes CHECK=test", "PUPPET_VERSION=\"~> 4.8.0\" STRICT_VARIABLES=yes CHECK=test", "PUPPET_VERSION=\"~> 4.9.0\" STRICT_VARIABLES=yes CHECK=test", "PUPPET_VERSION=\"~> 4.10.0\" STRICT_VARIABLES=yes CHECK=test", "PUPPET_VERSION=\"~> 5.0.0\" STRICT_VARIABLES=yes CHECK=test"]
rvm: [2.2, 2.3, 2.4]
matrix:
  fast_finish: true
 
  exclude:
  - rvm: 2.2
    env: CHECK=rubocop
  include:
  - rvm: 2.3
    bundler_args: --without development
    dist: trusty
    env: BEAKER_TESTMODE=apply BEAKER_set=docker/ubuntu-14.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.3
    bundler_args: --without development
    dist: trusty
    env: BEAKER_TESTMODE=apply BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=build DEPLOY_TO_FORGE=yes
notifications:
  email: false
deploy:
  provider: puppetforge
  deploy:
    branch: ha-bug-puppet-forge
  user: icann
  password:
    secure: "f5bYcp02Gw4fT2ik5QognnjTipc76L2t4WE+5IE82qGHpz07GKEp0UewYcRtx8gW5pT5n+2DCiBPPKjLv3d95hW+4ttGrHuWMHpRyvWtFmQArPPvX1uxmpn4MJDrITIge7Ky27iy3JfKXmzMVjQ0/GMbUZPxbsun7pAtpZQAWi2dZWq4/ZZ2KmK5l29cItO31+72ZCbz0jYQDxz7H7sCORQqfdpsHr3n1HLm/qs717Ca9VxVEWagKBso29WSEhEnB9xTnFABp02d44+OwTxAwwDiFtPymu6PTLpOD3YErf57txnMjtUavW84/hjdcLovCNLkz5tHRkpVnICCXZ3AtvQ4sFFmzX407Xm1EsIBvxq3VcYJ5EfydKv5NNEaYgVIBGl+sdaRxKIdj2Y0senoVKMwjcTCB8EijigUwPaPeh/iHYVl9Wah4yll9RN5tvWrFm2Pho8Diqeue/MKN/lrbgZ0f1L9UfCOatbBxdL+D+ZYyC10dIZ/v4AXTmK2eDD0GEpH0PiKgPVIJNh9DeJGUMg7JDZLlLWMNUiis5kZuCVVr4aMCpJNYEKdDL/pU7dIy82OamgDVV3yA0YUixo7zxUawG1bhmvSqPdrErvjNvqKDP8QIFUCRKbhUqzFKEaYiBd6LAugjZJU1Yd+P1/vqu7ugNNDPN4bSKdQuq+pE1E="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
