---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.10
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0"
jobs:
  fast_finish: true
  include:
    - stage: spec and lint
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - stage: spec and lint
      env: CHECK=parallel_spec
    - stage: spec and lint
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-14.04 BEAKER_TESTMODE=apply TEST_TIERS=low
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-16.04 BEAKER_TESTMODE=apply TEST_TIERS=low
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/centos-7 BEAKER_TESTMODE=apply TEST_TIERS=low
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-14.04 BEAKER_TESTMODE=apply TEST_TIERS=medium
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-16.04 BEAKER_TESTMODE=apply TEST_TIERS=medium
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/centos-7 BEAKER_TESTMODE=apply TEST_TIERS=medium
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-14.04 BEAKER_TESTMODE=apply TEST_TIERS=high
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: acceptence
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-16.04 BEAKER_TESTMODE=apply TEST_TIERS=high
      rvm: 2.4.10
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - stage: deploy
      env: PUPPET_VERSION="~> 4.0" CHECK=build DEPLOY_TO_FORGE=yes
notifications:
  email: false
deploy:
  provider: puppetforge
  user: icann
  password:
    secure: "f5bYcp02Gw4fT2ik5QognnjTipc76L2t4WE+5IE82qGHpz07GKEp0UewYcRtx8gW5pT5n+2DCiBPPKjLv3d95hW+4ttGrHuWMHpRyvWtFmQArPPvX1uxmpn4MJDrITIge7Ky27iy3JfKXmzMVjQ0/GMbUZPxbsun7pAtpZQAWi2dZWq4/ZZ2KmK5l29cItO31+72ZCbz0jYQDxz7H7sCORQqfdpsHr3n1HLm/qs717Ca9VxVEWagKBso29WSEhEnB9xTnFABp02d44+OwTxAwwDiFtPymu6PTLpOD3YErf57txnMjtUavW84/hjdcLovCNLkz5tHRkpVnICCXZ3AtvQ4sFFmzX407Xm1EsIBvxq3VcYJ5EfydKv5NNEaYgVIBGl+sdaRxKIdj2Y0senoVKMwjcTCB8EijigUwPaPeh/iHYVl9Wah4yll9RN5tvWrFm2Pho8Diqeue/MKN/lrbgZ0f1L9UfCOatbBxdL+D+ZYyC10dIZ/v4AXTmK2eDD0GEpH0PiKgPVIJNh9DeJGUMg7JDZLlLWMNUiis5kZuCVVr4aMCpJNYEKdDL/pU7dIy82OamgDVV3yA0YUixo7zxUawG1bhmvSqPdrErvjNvqKDP8QIFUCRKbhUqzFKEaYiBd6LAugjZJU1Yd+P1/vqu7ugNNDPN4bSKdQuq+pE1E="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
